/*
Neucore API

Client library of Neucore API

API version: 1.43.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package neucoreapi

import (
	"encoding/json"
)

// PluginConfigurationURL struct for PluginConfigurationURL
type PluginConfigurationURL struct {
	// placeholders: {plugin_id}, {username}, {password}, {email}
	Url string `json:"url"`
	Title string `json:"title"`
	Target string `json:"target"`
}

// NewPluginConfigurationURL instantiates a new PluginConfigurationURL object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPluginConfigurationURL(url string, title string, target string) *PluginConfigurationURL {
	this := PluginConfigurationURL{}
	this.Url = url
	this.Title = title
	this.Target = target
	return &this
}

// NewPluginConfigurationURLWithDefaults instantiates a new PluginConfigurationURL object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPluginConfigurationURLWithDefaults() *PluginConfigurationURL {
	this := PluginConfigurationURL{}
	return &this
}

// GetUrl returns the Url field value
func (o *PluginConfigurationURL) GetUrl() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Url
}

// GetUrlOk returns a tuple with the Url field value
// and a boolean to check if the value has been set.
func (o *PluginConfigurationURL) GetUrlOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Url, true
}

// SetUrl sets field value
func (o *PluginConfigurationURL) SetUrl(v string) {
	o.Url = v
}

// GetTitle returns the Title field value
func (o *PluginConfigurationURL) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *PluginConfigurationURL) GetTitleOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *PluginConfigurationURL) SetTitle(v string) {
	o.Title = v
}

// GetTarget returns the Target field value
func (o *PluginConfigurationURL) GetTarget() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Target
}

// GetTargetOk returns a tuple with the Target field value
// and a boolean to check if the value has been set.
func (o *PluginConfigurationURL) GetTargetOk() (*string, bool) {
	if o == nil {
    return nil, false
	}
	return &o.Target, true
}

// SetTarget sets field value
func (o *PluginConfigurationURL) SetTarget(v string) {
	o.Target = v
}

func (o PluginConfigurationURL) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["url"] = o.Url
	}
	if true {
		toSerialize["title"] = o.Title
	}
	if true {
		toSerialize["target"] = o.Target
	}
	return json.Marshal(toSerialize)
}

type NullablePluginConfigurationURL struct {
	value *PluginConfigurationURL
	isSet bool
}

func (v NullablePluginConfigurationURL) Get() *PluginConfigurationURL {
	return v.value
}

func (v *NullablePluginConfigurationURL) Set(val *PluginConfigurationURL) {
	v.value = val
	v.isSet = true
}

func (v NullablePluginConfigurationURL) IsSet() bool {
	return v.isSet
}

func (v *NullablePluginConfigurationURL) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePluginConfigurationURL(val *PluginConfigurationURL) *NullablePluginConfigurationURL {
	return &NullablePluginConfigurationURL{value: val, isSet: true}
}

func (v NullablePluginConfigurationURL) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePluginConfigurationURL) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


