/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// SystemVariable struct for SystemVariable
type SystemVariable struct {
	// Variable name.
	Name string `json:"name"`
	// Variable value.
	Value *string `json:"value"`
}
