/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
import (
	"time"
)
// RemovedCharacter struct for RemovedCharacter
type RemovedCharacter struct {
	NewPlayerId int32 `json:"newPlayerId,omitempty"`
	NewPlayerName string `json:"newPlayerName,omitempty"`
	Player Player `json:"player,omitempty"`
	// EVE character ID.
	CharacterId int64 `json:"characterId"`
	// EVE character name.
	CharacterName string `json:"characterName"`
	// Date of removal.
	RemovedDate time.Time `json:"removedDate"`
	// How it was removed (deleted or moved to another account).
	Reason string `json:"reason"`
	DeletedBy Player `json:"deletedBy,omitempty"`
}
