/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// Watchlist struct for Watchlist
type Watchlist struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	LockWatchlistSettings bool `json:"lockWatchlistSettings,omitempty"`
}
