/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// Alliance struct for Alliance
type Alliance struct {
	// EVE alliance ID.
	Id int64 `json:"id"`
	// EVE alliance name.
	Name *string `json:"name"`
	// Alliance ticker.
	Ticker *string `json:"ticker"`
	// Groups for automatic assignment (API: not included by default).
	Groups []Group `json:"groups,omitempty"`
}
