/*
Neucore API

Client library of Neucore API

API version: 1.33.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package neucoreapi

import (
	"encoding/json"
)

// EsiType An EVE name from the category \"inventory_type\".
type EsiType struct {
	Id int64 `json:"id"`
	Name string `json:"name"`
}

// NewEsiType instantiates a new EsiType object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEsiType(id int64, name string) *EsiType {
	this := EsiType{}
	this.Id = id
	this.Name = name
	return &this
}

// NewEsiTypeWithDefaults instantiates a new EsiType object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEsiTypeWithDefaults() *EsiType {
	this := EsiType{}
	return &this
}

// GetId returns the Id field value
func (o *EsiType) GetId() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *EsiType) GetIdOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *EsiType) SetId(v int64) {
	o.Id = v
}

// GetName returns the Name field value
func (o *EsiType) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *EsiType) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *EsiType) SetName(v string) {
	o.Name = v
}

func (o EsiType) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["name"] = o.Name
	}
	return json.Marshal(toSerialize)
}

type NullableEsiType struct {
	value *EsiType
	isSet bool
}

func (v NullableEsiType) Get() *EsiType {
	return v.value
}

func (v *NullableEsiType) Set(val *EsiType) {
	v.value = val
	v.isSet = true
}

func (v NullableEsiType) IsSet() bool {
	return v.isSet
}

func (v *NullableEsiType) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEsiType(val *EsiType) *NullableEsiType {
	return &NullableEsiType{value: val, isSet: true}
}

func (v NullableEsiType) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEsiType) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


