/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
import (
	"time"
)
// Corporation struct for Corporation
type Corporation struct {
	// EVE corporation ID.
	Id int64 `json:"id"`
	// EVE corporation name.
	Name *string `json:"name"`
	// Corporation ticker.
	Ticker *string `json:"ticker"`
	Alliance Alliance `json:"alliance,omitempty"`
	// Groups for automatic assignment (API: not included by default).
	Groups []Group `json:"groups,omitempty"`
	// Last update of corporation member tracking data (API: not included by default).
	TrackingLastUpdate *time.Time `json:"trackingLastUpdate,omitempty"`
	// True if this corporation was automatically placed on the allowlist of a watchlist (API: not included by default).
	AutoAllowlist bool `json:"autoAllowlist,omitempty"`
}
