/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// Player struct for Player
type Player struct {
	Id int32 `json:"id"`
	// A name for the player.  This is the EVE character name of the current main character or of the last main character if there is currently none.
	Name string `json:"name"`
	// Player account status.
	Status string `json:"status,omitempty"`
	// Roles for authorization.
	Roles []Role `json:"roles,omitempty"`
	Characters []Character `json:"characters,omitempty"`
	// Group membership.
	Groups []Group `json:"groups,omitempty"`
	// Manager of groups.
	ManagerGroups []Group `json:"managerGroups,omitempty"`
	// Manager of apps.
	ManagerApps []App `json:"managerApps,omitempty"`
	// Characters that were removed from a player (API: not included by default).
	RemovedCharacters []RemovedCharacter `json:"removedCharacters,omitempty"`
	// Characters that were moved from another player account to this account (API: not included by default).
	IncomingCharacters []RemovedCharacter `json:"incomingCharacters,omitempty"`
}
