/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// App struct for App
type App struct {
	// App ID
	Id int32 `json:"id"`
	// App name
	Name string `json:"name"`
	// Roles for authorization.
	Roles []Role `json:"roles,omitempty"`
	// Groups the app can see.
	Groups []Group `json:"groups,omitempty"`
}
