/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
import (
	"time"
)
// Character struct for Character
type Character struct {
	// EVE character ID.
	Id int64 `json:"id"`
	// EVE character name.
	Name string `json:"name"`
	Main bool `json:"main,omitempty"`
	// Shows if character's refresh token is valid or not.  This is null if there is no refresh token (EVE SSOv1 only) or a valid token but without scopes (SSOv2).
	ValidToken *bool `json:"validToken,omitempty"`
	// Date and time when that valid token property was last changed.
	ValidTokenTime *time.Time `json:"validTokenTime,omitempty"`
	Created *time.Time `json:"created,omitempty"`
	// Last ESI update.
	LastUpdate *time.Time `json:"lastUpdate,omitempty"`
	Corporation Corporation `json:"corporation,omitempty"`
}
