/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// Group struct for Group
type Group struct {
	// Group ID.
	Id int32 `json:"id"`
	// A unique group name (can be changed).
	Name string `json:"name"`
	Visibility string `json:"visibility,omitempty"`
}
