/*
Neucore API

Client library of Neucore API

API version: 2.4.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package neucoreapi

import (
	"encoding/json"
)

// checks if the PlayerWithCharcterId type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PlayerWithCharcterId{}

// PlayerWithCharcterId struct for PlayerWithCharcterId
type PlayerWithCharcterId struct {
	Id int32 `json:"id"`
	Name string `json:"name"`
	CharacterId int32 `json:"characterId"`
}

// NewPlayerWithCharcterId instantiates a new PlayerWithCharcterId object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPlayerWithCharcterId(id int32, name string, characterId int32) *PlayerWithCharcterId {
	this := PlayerWithCharcterId{}
	this.Id = id
	this.Name = name
	this.CharacterId = characterId
	return &this
}

// NewPlayerWithCharcterIdWithDefaults instantiates a new PlayerWithCharcterId object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPlayerWithCharcterIdWithDefaults() *PlayerWithCharcterId {
	this := PlayerWithCharcterId{}
	return &this
}

// GetId returns the Id field value
func (o *PlayerWithCharcterId) GetId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PlayerWithCharcterId) GetIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PlayerWithCharcterId) SetId(v int32) {
	o.Id = v
}

// GetName returns the Name field value
func (o *PlayerWithCharcterId) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *PlayerWithCharcterId) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *PlayerWithCharcterId) SetName(v string) {
	o.Name = v
}

// GetCharacterId returns the CharacterId field value
func (o *PlayerWithCharcterId) GetCharacterId() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.CharacterId
}

// GetCharacterIdOk returns a tuple with the CharacterId field value
// and a boolean to check if the value has been set.
func (o *PlayerWithCharcterId) GetCharacterIdOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CharacterId, true
}

// SetCharacterId sets field value
func (o *PlayerWithCharcterId) SetCharacterId(v int32) {
	o.CharacterId = v
}

func (o PlayerWithCharcterId) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PlayerWithCharcterId) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["name"] = o.Name
	toSerialize["characterId"] = o.CharacterId
	return toSerialize, nil
}

type NullablePlayerWithCharcterId struct {
	value *PlayerWithCharcterId
	isSet bool
}

func (v NullablePlayerWithCharcterId) Get() *PlayerWithCharcterId {
	return v.value
}

func (v *NullablePlayerWithCharcterId) Set(val *PlayerWithCharcterId) {
	v.value = val
	v.isSet = true
}

func (v NullablePlayerWithCharcterId) IsSet() bool {
	return v.isSet
}

func (v *NullablePlayerWithCharcterId) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePlayerWithCharcterId(val *PlayerWithCharcterId) *NullablePlayerWithCharcterId {
	return &NullablePlayerWithCharcterId{value: val, isSet: true}
}

func (v NullablePlayerWithCharcterId) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePlayerWithCharcterId) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


