/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// EsiLocation struct for EsiLocation
type EsiLocation struct {
	Id int64 `json:"id"`
	Category string `json:"category"`
	Name string `json:"name"`
}
