/*
 * Neucore API
 *
 * Client library of Neucore API
 *
 * API version: 1.14.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package neucoreapi
// CharacterGroups struct for CharacterGroups
type CharacterGroups struct {
	Character Character `json:"character"`
	Groups []Group `json:"groups"`
}
